name: devops project 4

on: push
jobs:
  devops4-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Insetall dependencies 
        run: pip install -r requirements.txt

      - name: Formatting test
        run: black .

      - name: Lint test
        run: flake8 .

      - name: Static analysis 
        run: bandit -r . --skip B201,B101,B104
